config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  resources :users
  resources :articles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'articles#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.admin?  # additional permissions for administrators
      can :manage, :all
      can :destroy, :all
    else
      can [:show, :index], Article
      can :manage, User, id: user.id
      # can :manage, Article, :user_id => user.id
      cannot :destroy, :all
    end
  end
end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  # belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # has_many :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_url, alert: exception.message
  end

  def authenticate_user!
    redirect_back(fallback_location: articles_url, alert: 'Only Admins can make changes') unless user_signed_in?
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'The article is up' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'The new version is up' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content, :contributor, :image_url, :time, :preview, :site, :momentum)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    redirect_to edit_user_registration_path
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 articles-display">

<!-- <#% cache article do %> -->

  <section class="articles-background">

    <br></br>

    <%= image_tag(article.image_url, class: "img-responsive articles-pix") unless article.image_url.nil? %>
    <br>
    <section class="articles-framed">
    <h3 class="jumbotron momentum-jumbotron" id="articles-momentum">&nbsp;<%= article.momentum %></h3>
    <br>
    <h3 id="articles-title"><%= link_to "#{article.title}", article %></h3>
    <br>
    <p id="articles-preview"><%= article.preview %></p>
    <br>
    <p id="articles-time"><%= article.time %><br><span><i>'Berlin' zone</i></span></p>
    <br>
    <strong><p class="jumbotron contributor-jumbotron" id="articles-contributor"><span id="articles-site"><%= article.site %></span><br><span id="articles-author">by&nbsp;<%= article.contributor %></span></p></strong>
    </section>

    <br class="titles-spread"></br>
    <br class="titles-spread">

      <span class="links-articles show-articles"><%= link_to 'Show', article %></span>

    <% if signed_in? && current_user.admin? %>
      <span class="links-articles edit-articles">
        <%= link_to 'Edit', edit_article_path(article) %>
      </span>
      <span class="links-articles delete-articles">
        <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %>
      </span>
    <% end %>

    <br class="titles-spread"></br>
    <br class="titles-spread"></br>

  </section><!-- end articles-background -->

<!-- <#% end %> -->
</div><!-- /col -->

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true, id:"edit-articles") do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :momentum %>
    <%= form.text_field :momentum, :class => "edit-boxes" %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, :class => "edit-boxes" %>
  </div>

  <div class="field">
    <%= form.label :preview %>
    <%= form.text_area :preview, :class => "edit-content" %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, :class => "edit-content" %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, :class => "edit-boxes" %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.datetime_select :time %>
  </div>

  <div class="field">
    <%= form.label :site %>
    <%= form.text_field :site, :class => "edit-boxes" %>
  </div>

  <div class="field">
    <%= form.label :contributor %>
    <%= form.text_field :contributor, :class => "edit-boxes" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<br>
<br>

<h2 id="editing-title">Editing Article</h2>

<%= render 'form', article: @article %>

<div class="links-articles-form">
  <%= link_to 'Show', @article, :class => "links-edit"  %> |
  <%= link_to 'Back', :back, :class => "links-edit"  %>
  <%#= link_to 'Back', articles_path, :class => "links-edit"  %>
</div>

<br>

app/views/articles/index.html.erb
<!-- <br>
<br> -->

<!-- <p id="notice"><#%= notice %></p>
<p id="alert"><#%= alert %></p> -->

<section id="main-page">

<div class="jumbotron" id="main-jumbotron">
  <h1>
  MDMIX BLOG
  </h1>
</div>

<div class="row title-row" id="title-on-video">
  <div class="col-xs-12 all-videos">
    <span class="home-videos col-lg-4 col-md-4 col-sm-4 col-xs-4">
    <%= video_tag(["PresidentsMen-forStreaming.mp4"], :id => "home-video-left", :controls => false, :autoplay => true, :loop => true, :muted => true, :type => "video/mp4") %>
    </span>
    <span class="home-videos col-lg-4 col-md-4 col-sm-4 col-xs-4">
    <%= video_tag(["PresidentsMen-forStreaming.mp4"], :id => "home-video-center", :controls => false, :autoplay => true, :loop => true, :muted => true, :type => "video/mp4") %>
    </span>
    <span class="home-videos col-lg-4 col-md-4 col-sm-4 col-xs-4">
    <%= video_tag(["PresidentsMen-forStreaming.mp4"], :id => "home-video-right", :controls => false, :autoplay => true, :loop => true, :muted => true, :type => "video/mp4") %>
    </span>
    <div id="home-title">
      <h1>
      NEWS MOMENTUM
      </h1>
    </div>
  </div>
</div>

<!-- <br class="titles-spread">
<br class="titles-spread">
<br class="titles-spread">
<br class="titles-spread"> -->

<div class="jumbotron" id="sub-jumbotron">
  <h2 id="generated-title">GENERATED BY THE MEDIA AND US
  <br>
  <span id="work-progress">(work in progress)</span></h2>
</div>

<!-- <br class="titles-spread">
<br class="titles-spread">
<br class="titles-spread">
<br class="titles-spread">

<h3>People: 'Most Read'</h3> -->


<br class="titles-spread">
<br class="titles-spread">
<br class="titles-spread">

<!-- <hr class="line-breaks"> -->
<!-- <#% if signed_in? && current_user.admin? %> -->
<div class="jumbotron new-jumbotron" id="new-articles">
  <%= link_to 'NEW BLOG POST', new_article_path %>
</div>
<!-- <#% end %> -->
<!-- <hr class="line-breaks"> -->
<!-- <br>
<br>
<h5>Blog Posts</h5> -->

<div class="container-fluid articles-overview">
  <div class="row articles-row">
  <!-- <#% cache(cache_key_for_articles) do %> -->
    <%= render @articles %>
  <!-- <#% end %> -->
  </div>
</div>

<br>

</section>

app/views/articles/new.html.erb
<br>
<br>

<h2 id="creating-title">New Article</h2>

<%= render 'form', article: @article %>

<div class="links-articles-form">
  <%= link_to 'Back', articles_path %>
</div>

<br>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<section class="actual-articles-background" data-article-id="<%= @article.id %>">

  <p class="newly-created articles-pix">
    <span id="articles-image_url"><%= image_tag(@article.image_url, class: "img-zoom img-responsive articles-pix", data_zoom_image: 'image_tag(@article.big_image_url)' ) unless @article.image_url.nil? %></span>
    <!-- also possible: 'image_tag(@article.image_url(:large))' -->
  </p>

  <hr class="pix-lines">

  <section class="articles-framed">
  <p class="newly-created jumbotron momentum-jumbotron" id="momentum-jumbotron">
    <span id="articles-momentum"><%= @article.momentum %></span>
  </p>

  <p class="newly-created" id="titles-frame">
    <span id="articles-title"><%= @article.title %></span>
  </p>

  <p class="newly-created actual-content">
    <span id="articles-content"><%= @article.content %></span>
  </p>

  <p class="newly-created">
    <span id="articles-time"><%= @article.time %></span>
  </p>

  <p class="newly-created jumbotron contributor-jumbotron">
    <span id="articles-site"><%= @article.site %></span>
    <span id="articles-contributor">by <%= @article.contributor %></span>
  </p>

  <br></br>

  <% if signed_in? && current_user.admin? %>
    <span class="links-articles edit-articles">
      <%= link_to 'Edit', edit_article_path(@article) %>
    </span>
  <% end %>
    &nbsp;&nbsp;&nbsp;<span class="links-articles">
      <%= link_to 'Back', articles_path %>
    </span>

  </section>

  <br></br>

</section>


<!--
Backup
 -->
<!-- <p>
  <strong>Title:</strong>
  <#%= @article.title %>
</p>

<p>
  <strong>Content:</strong>
  <#%= @article.content %>
</p>

<p>
  <strong>Image url:</strong>
  <#%= @article.image_url %>
</p>

<p>
  <strong>Time:</strong>
  <#%= @article.time %>
</p>

<p>
  <strong>Site:</strong>
  <#%= @article.contributor %>
</p>

<p>
  <strong>Contributor:</strong>
  <#%= @article.contributor %>
</p> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>mdmixblog</title>

    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat|Josefin+Sans|Arvo|Miriam+Libre|Fira+Mono|Anonymous+Pro  ">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <!-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  </head>

  <body>

    <main class="page-wrap">

      <!--navbar starts here-->
      <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation" id="navbar">
        <div class="container-fluid nav-fluid" id="nav-fluid">
          <div class="navbar-header" id="nav-header">
            <!-- <button type="button" class="navbar-toggle" data-toggle="collapse"
              data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button> -->
            <div class="mdmix navbar-brand">
              <%= link_to "MAIN", root_path %>
              <!-- <span class="separator">|</span> -->
              <!-- <span><hr id="menu-separator"></span> -->
            </div><!--end mdmix -->
            <ul class="navbar-nav user-porthole">
              <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-link user-login") %>
              </li>
              <% else %>
              <li class="nav-item">
                <%= link_to('Admins', new_user_session_path, class: "nav-link user-login") %>
              </li>
              <% end %>
            </ul>
          </div><!-- navbar header -->
          <!-- <div class="navbar-collapse collapse nav-box" id="nav-box"> -->
            <!-- <ul class="nav navbar-nav navbar-right"> -->

            <!-- </ul> -->
          <!-- </div><!-- end nav -->
        <!-- </div><!-- end nav container -->
      </nav><!-- end navbar-->
      <div class="anchor">
      </div>
      <br>
      <br>

      <div class="alerts-notices">
      <% if alert %>
        <p class="alert alert-warning"><%= alert %></p>
      <% end %>

      <% if notice %>
        <p id="notice" class="alert alert-warning"><%= notice %></p>
      <% end %>
      </div>

      <%= yield %>

    </main>

      <footer>
        <span>&copy; 2019 MDMIXblog – News Momentum</span>
      </footer>

  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<br>
<br>
<br>
<h2 id="users-together">Users</h2>

  <div class="container-fluid all-users">
    <% @users.each do |user| %>
      <div class="row users-row">
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 users-emails">
          <p class="users-details"><%= user.email %></p>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 users-show">
          <span><%= link_to 'Show', user, class: "users-changes" %></span>

          <span><%= link_to 'Edit', edit_user_path(user), class: "users-changes" %></span>

          <span><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class: "users-changes" %></span>
        </div>
      </div>
    <% end %>
  </div>

<br>

<div class="link-table">
  <%= link_to 'New User', new_user_path, class: "links-users" %>
</div>
<br>
<br>

app/views/users/indexb.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<br>
<br>
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>